version: '3.8'
services:
  aggregator-api:
    image: kybernetique/aggregator-api:latest
    ports:
      - "8081:8080"
    networks:
      backend:
        aliases:
          - "aggregator"


  parser-api:
    image: kybernetique/parser-api:latest
    ports:
      - "8082:8080"
    networks:
      backend:
        aliases:
          - "parser"

  postgres:
    image: postgres:14.1
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "aggregator_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    networks:
      backend:
        aliases:
          - "postgres"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      backend:
        aliases:
          - "nginx"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - aggregator-api
      - parser-api
      - postgres

networks:
  backend:
    driver: bridge